# This file is part of the ORBS distribution.
# See the file LICENSE.TXT for more information.

all: gcc -Wall -I/usr/include/python3.7 -lpython3.7 utilsmodule.c -o Utilc time64
#gcc -Wall -I/usr/include/python3.7 -lpython3.7 utilsmodule.c -o Utilc
clean:
	rm -f time64
